spring:
  h2:
    console:
      enabled: true
      path: '/console'
  main:
    banner-mode: off
  datasource:
    url: 'jdbc:h2:file:C:/Users/ganzes/Desktop/toDoAppSpringUC/toDoAppSpringUC/todo-db'