  spring:
    h2:
      console:
        enabled: true
        path: '/console'
    datasource:
      url: 'jdbc:h2:file:C:/Users/ganzes/Desktop/toDoAppSpringUC/toDoAppSpringUC/todo-db'

    jpa:
      hibernate:
        ddl-auto: update